replicaCount: 1

image:
  repository: hasanroo10/node-app
  tag: v1.0.1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: node-app.127.0.0.1.nip.io
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}
