apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-app.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
  selector:
    app.kubernetes.io/name: {{ include "node-app.name" . }}
