replicaCount: 1

image:
  repository: hasanroo10/go-app
  pullPolicy: IfNotPresent
  tag: v1.0.1

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: go-app.127.0.0.1.nip.io
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}
